Add sushytools scale up in dev-env
Nordix/metal3-clusterapi-docs pull request #74
Opened 2023-01-09 12:11 UTC by mboukhalfa

2023-01-10 09:19 UTC, tuminoid requested changes
some typos

2023-01-10 09:19 UTC, tuminoid commented on Support/sushytools/scale-to-2-instances.md
> +eg: `curl http://localhost:8000/redfish/v1/Systems/`S
Extra-S at end of line

2023-01-10 09:54 UTC, mboukhalfa commented on Support/sushytools/scale-to-2-instances.md
> +eg: `curl http://localhost:8000/redfish/v1/Systems/`S
fixed

2023-01-10 09:54 UTC, mboukhalfa commented on Support/sushytools/scale-to-2-instances.md
> +To scale up the sushy-tools instances it suffices to run multiple instaces of the container and configure a different port in the sushy-tools configfile  for each instance. BMO use the bmh spec  to g
fixed

2023-01-25 08:57 UTC, lentzi90 submitted a review, later dismissed

2023-01-25 08:57 UTC, lentzi90 commented on Support/sushytools/scale-to-2-instances.md
> +Dev-env supports redfish BMC using sushy-tools running in a container and building its the image from [https://github.com/metal3-io/ironic-image/tree/main/resources/sushy-tools](https://github.com/me
nit
```suggestion
Dev-env supports redfish BMC using sushy-tools running in a container and building the image from [https://github.com/metal3-io/ironic-image/tree/main/resources/sushy-tools](https://github.com/metal3-io/ironic-image/tree/main/resources/sushy-tools). To select redfish virtual media in the dev-env export the BMC driver environment variable `export BMC_DRIVER="redfish-virtualmedia"`.
```

2023-01-25 09:05 UTC, lentzi90 submitted a review, later dismissed

2023-01-25 09:10 UTC, smoshiur1237 requested changes
Nit

2023-01-25 09:10 UTC, smoshiur1237 commented on Support/sushytools/scale-to-2-instances.md
> +Sushy-tools is backed with libvirt, and by default it listens to redfish requests on the port `8000`. An instance of sushy-tools sees all the libvirt domains that means multiple instances will be abl
```suggestion
Sushy-tools is backed by libvirt and it listens to redfish requests on the port `8000` by default. An instance of sushy-tools can see all the libvirt domains and that means multiple instances will be able to see the same domains.
```

2023-01-25 09:10 UTC, smoshiur1237 commented on Support/sushytools/scale-to-2-instances.md
> +To scale up the sushy-tools instances it suffices to run multiple instances of the container and configure a different port for each instance in the sushy-tools configfile.
```suggestion
To scale up the sushy-tools instances, it suffices to run multiple instances of the container and configure a different port for each instance in the sushy-tools configfile.
```

2023-01-25 09:22 UTC, smoshiur1237 reviewed
LGTM

2023-01-27 10:50 UTC, furkatgofurov7 commented on Support/sushytools/scale-to-2-instances.md
> +eg: `curl http://localhost:8000/redfish/v1/Systems/`
```suggestion
e.g.: `curl http://localhost:8000/redfish/v1/Systems/`
```

2023-01-27 10:50 UTC, furkatgofurov7 commented on Support/sushytools/scale-to-2-instances.md
> +To scale up the sushy-tools instances, it suffices to run multiple instances of the container and configure a different port for each instance in the sushy-tools configfile.
```suggestion
To scale up the sushy-tools instances, it is sufficient to run multiple instances of the container and configure a different port for each instance in the sushy-tools configfile.
```

2023-02-09 10:23 UTC, mboukhalfa commented on Support/sushytools/scale-to-2-instances.md
> +To scale up the sushy-tools instances, it suffices to run multiple instances of the container and configure a different port for each instance in the sushy-tools configfile.
fixed

2023-02-09 10:23 UTC, mboukhalfa commented on Support/sushytools/scale-to-2-instances.md
> +eg: `curl http://localhost:8000/redfish/v1/Systems/`
fixed

2023-02-09 11:33 UTC, smoshiur1237 reviewed
LGTM

2023-02-09 11:37 UTC, lentzi90 reviewed
/lgtm

2023-02-15 11:40 UTC, furkatgofurov7 approved these changes

2023-02-15 12:14 UTC, smoshiur1237 approved these changes

2023-02-15 12:16 UTC, tuminoid approved these changes

2023-02-15 12:17 UTC, merged